// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto_AutoMobile.Data;

#nullable disable

namespace Projeto_AutoMobile.Migrations
{
    [DbContext(typeof(Projeto_AutoMobileContext))]
    [Migration("20260513194957_inicial")]
    partial class inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Projeto_AutoMobile.Data.Projeto_AutoMobile.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CartaConducao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NIF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telemovel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Projeto_AutoMobile.Data.Projeto_AutoMobile.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAtual")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("Projeto_AutoMobile.Data.Projeto_AutoMobile.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<double>("PrecoEstimado")
                        .HasColumnType("float");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Projeto_AutoMobile.Data.Projeto_AutoMobile.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataDisponibilidade")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PrecoDia")
                        .HasPrecision(8, 2)
                        .HasColumnType("float(8)");

                    b.Property<string>("TipoVeiculo")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Veiculos");

                    b.HasDiscriminator<string>("TipoVeiculo").HasValue("Veiculo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Projeto_AutoMobile.Data.Projeto_AutoMobile.Camiao", b =>
                {
                    b.HasBaseType("Projeto_AutoMobile.Data.Projeto_AutoMobile.Veiculo");

                    b.Property<int>("MaxCarga")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Camiao");
                });

            modelBuilder.Entity("Projeto_AutoMobile.Data.Projeto_AutoMobile.Camioneta", b =>
                {
                    b.HasBaseType("Projeto_AutoMobile.Data.Projeto_AutoMobile.Veiculo");

                    b.Property<int>("Eixos")
                        .HasColumnType("int");

                    b.Property<int>("MaxPassageiros")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Camioneta");
                });

            modelBuilder.Entity("Projeto_AutoMobile.Data.Projeto_AutoMobile.Carro", b =>
                {
                    b.HasBaseType("Projeto_AutoMobile.Data.Projeto_AutoMobile.Veiculo");

                    b.Property<int>("Caixa")
                        .HasColumnType("int");

                    b.Property<int>("NrPortas")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Carro");
                });

            modelBuilder.Entity("Projeto_AutoMobile.Data.Projeto_AutoMobile.Mota", b =>
                {
                    b.HasBaseType("Projeto_AutoMobile.Data.Projeto_AutoMobile.Veiculo");

                    b.Property<string>("Cilindrada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Mota");
                });

            modelBuilder.Entity("Projeto_AutoMobile.Data.Projeto_AutoMobile.Reserva", b =>
                {
                    b.HasOne("Projeto_AutoMobile.Data.Projeto_AutoMobile.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projeto_AutoMobile.Data.Projeto_AutoMobile.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("Projeto_AutoMobile.Data.Projeto_AutoMobile.Veiculo", b =>
                {
                    b.HasOne("Projeto_AutoMobile.Data.Projeto_AutoMobile.Empresa", "Empresa")
                        .WithMany("Frota")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Projeto_AutoMobile.Data.Projeto_AutoMobile.Empresa", b =>
                {
                    b.Navigation("Frota");
                });
#pragma warning restore 612, 618
        }
    }
}
