// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto_AutoMobile.Data;

#nullable disable

namespace Projeto_AutoMobile.Migrations
{
    [DbContext(typeof(Projeto_AutoMobileContext))]
    partial class Projeto_AutoMobileContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Projeto_AutoMobile.Data.Projeto_AutoMobile.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CartaConducao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NIF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telemovel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Projeto_AutoMobile.Data.Projeto_AutoMobile.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAtual")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("Projeto_AutoMobile.Data.Projeto_AutoMobile.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataDisponibilidade")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecoDia")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Veiculos");

                    b.HasDiscriminator().HasValue("Veiculo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Projeto_AutoMobile.Data.Projeto_AutoMobile.Camiao", b =>
                {
                    b.HasBaseType("Projeto_AutoMobile.Data.Projeto_AutoMobile.Veiculo");

                    b.Property<int>("MaxCarga")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Camiao");
                });

            modelBuilder.Entity("Projeto_AutoMobile.Data.Projeto_AutoMobile.Camioneta", b =>
                {
                    b.HasBaseType("Projeto_AutoMobile.Data.Projeto_AutoMobile.Veiculo");

                    b.Property<int>("Eixos")
                        .HasColumnType("int");

                    b.Property<int>("MaxPassageiros")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Camioneta");
                });

            modelBuilder.Entity("Projeto_AutoMobile.Data.Projeto_AutoMobile.Carro", b =>
                {
                    b.HasBaseType("Projeto_AutoMobile.Data.Projeto_AutoMobile.Veiculo");

                    b.Property<int>("Caixa")
                        .HasColumnType("int");

                    b.Property<int>("NrPortas")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Carro");
                });

            modelBuilder.Entity("Projeto_AutoMobile.Data.Projeto_AutoMobile.Mota", b =>
                {
                    b.HasBaseType("Projeto_AutoMobile.Data.Projeto_AutoMobile.Veiculo");

                    b.Property<string>("Cilindrada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Mota");
                });

            modelBuilder.Entity("Projeto_AutoMobile.Data.Projeto_AutoMobile.Veiculo", b =>
                {
                    b.HasOne("Projeto_AutoMobile.Data.Projeto_AutoMobile.Empresa", "Empresa")
                        .WithMany("Frota")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Projeto_AutoMobile.Data.Projeto_AutoMobile.Empresa", b =>
                {
                    b.Navigation("Frota");
                });
#pragma warning restore 612, 618
        }
    }
}
